"""Generate the A29 OpenFOAM case from the Gen5 CAD and motor_model's operating point.

Nothing here is hand-entered. The velocity is motor_model's exit velocity, the geometry is the
STL the CAD package ships, and the domain is sized from the geometry's own bounding box. The
same rule validation/fem3d/ follows: a solve that describes a different machine from the one
being built is worse than no solve.

Two cases are written:
    free/       the assembly in an open stream
    channel/    the same assembly with the two stator plates present, which is how it runs

Usage:  python3 build_case.py [--fine]
"""
import argparse
import os
import struct
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "..")
sys.path.insert(0, os.path.join(ROOT, "analysis"))
import motor_model as mm  # noqa: E402

STL = os.path.join(ROOT, "cad", "stl")
BODY = ["VOLLEY_Sled_Gen5.stl", "VOLLEY_Payload_3U_Gen5.stl"]
PLATES = "VOLLEY_Stator_Gen5.stl"

RHO = 1.225        # kg/m^3, sea level, 15 C -- ISA
NU = 1.5e-5        # m^2/s, air
TURB_I = 0.01      # 1 % free-stream turbulence intensity, a still laboratory


def read_stl(path):
    """Binary STL -> (n_facets, vertices as (3n, 3) in metres)."""
    with open(path, "rb") as fh:
        fh.read(80)
        n = struct.unpack("<I", fh.read(4))[0]
        raw = np.frombuffer(fh.read(n * 50), dtype=np.uint8).reshape(n, 50)
        tri = raw[:, 12:48].copy().view("<f4").reshape(n, 3, 3)
    return n, tri.astype(np.float64) * 1e-3      # STL is in mm


def write_ascii_stl(path, name, tris):
    with open(path, "w") as fh:
        fh.write(f"solid {name}\n")
        for t in tris:
            nrm = np.cross(t[1] - t[0], t[2] - t[0])
            ln = np.linalg.norm(nrm)
            nrm = nrm / ln if ln > 0 else np.array([0.0, 0.0, 1.0])
            fh.write(f"  facet normal {nrm[0]:.6e} {nrm[1]:.6e} {nrm[2]:.6e}\n")
            fh.write("    outer loop\n")
            for v in t:
                fh.write(f"      vertex {v[0]:.6e} {v[1]:.6e} {v[2]:.6e}\n")
            fh.write("    endloop\n  endfacet\n")
        fh.write(f"endsolid {name}\n")


def frontal_area(tris, nx=400, nz=400):
    """Projected area on the plane normal to +x, by rasterising the triangles in (y, z).

    A bluff body's drag coefficient is meaningless without the area it is referenced to, and
    the projected area of this assembly is NOT the product of its bounding-box sides: the sled
    is wider than the payload and the payload sits proud of it.
    """
    yz = tris[:, :, 1:]
    ymin, zmin = yz.reshape(-1, 2).min(0)
    ymax, zmax = yz.reshape(-1, 2).max(0)
    ys = np.linspace(ymin, ymax, nx)
    zs = np.linspace(zmin, zmax, nz)
    Y, Z = np.meshgrid(ys, zs, indexing="ij")
    P = np.stack([Y.ravel(), Z.ravel()], 1)
    inside = np.zeros(len(P), dtype=bool)
    for t in yz:                                   # point-in-triangle, barycentric
        a, b, c = t
        v0, v1, v2 = c - a, b - a, P - a
        d00 = v0 @ v0
        d01 = v0 @ v1
        d11 = v1 @ v1
        den = d00 * d11 - d01 * d01
        if abs(den) < 1e-18:
            continue
        d02 = v2 @ v0
        d12 = v2 @ v1
        u = (d11 * d02 - d01 * d12) / den
        v = (d00 * d12 - d01 * d02) / den
        inside |= (u >= 0) & (v >= 0) & (u + v <= 1)
    cell = (ys[1] - ys[0]) * (zs[1] - zs[0])
    return float(inside.sum() * cell)


HEAD = """/*--------------------------------*- C++ -*----------------------------------*\\
| A29 ground-test air drag. GENERATED by validation/cfd/build_case.py.        |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


def wr(case, sub, obj, cls, body):
    d = os.path.join(case, sub)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, obj), "w") as fh:
        fh.write(HEAD.format(cls=cls, obj=obj))
        fh.write(body)


def build(case, tris, plates, U, fine):
    os.makedirs(os.path.join(case, "constant", "triSurface"), exist_ok=True)
    write_ascii_stl(os.path.join(case, "constant", "triSurface", "body.stl"), "body", tris)
    if plates is not None:
        write_ascii_stl(os.path.join(case, "constant", "triSurface", "plates.stl"),
                        "plates", plates)

    lo = tris.reshape(-1, 3).min(0)
    hi = tris.reshape(-1, 3).max(0)
    L = float(hi[0] - lo[0])
    # Domain sized from the body: 2L upstream, 5L downstream (the wake needs room), and
    # +-4 half-heights laterally, which holds blockage near 1 % -- low enough that the
    # free case really is free, and the only confinement in the channel case is the plates.
    x0, x1 = lo[0] - 2 * L, hi[0] + 5 * L
    half = max(hi[1] - lo[1], hi[2] - lo[2]) * 4.0
    cy = 0.5 * (lo[1] + hi[1])
    cz = 0.5 * (lo[2] + hi[2])
    y0, y1 = cy - half, cy + half
    z0, z1 = cz - half, cz + half

    h = (0.055 if fine else 0.080)                 # background cell size, m
    nx = max(int(round((x1 - x0) / h)), 10)
    ny = max(int(round((y1 - y0) / h)), 10)
    nz = max(int(round((z1 - z0) / h)), 10)

    wr(case, "system", "blockMeshDict", "dictionary", f"""
scale 1;
vertices
(
    ({x0} {y0} {z0}) ({x1} {y0} {z0}) ({x1} {y1} {z0}) ({x0} {y1} {z0})
    ({x0} {y0} {z1}) ({x1} {y0} {z1}) ({x1} {y1} {z1}) ({x0} {y1} {z1})
);
blocks ( hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1) );
edges ();
boundary
(
    inlet  {{ type patch;  faces ((0 4 7 3)); }}
    outlet {{ type patch;  faces ((1 2 6 5)); }}
    farfield {{ type patch; faces ((0 1 5 4) (3 7 6 2) (0 3 2 1) (4 5 6 7)); }}
);
mergePatchPairs ();
""")

    lvl = (5 if fine else 4)
    geom = '    body.stl { type triSurfaceMesh; name body; }\n'
    refs = f'        body {{ level ({lvl-1} {lvl}); patchInfo {{ type wall; }} }}\n'
    if plates is not None:
        geom += '    plates.stl { type triSurfaceMesh; name plates; }\n'
        refs += f'        plates {{ level ({lvl-2} {lvl-1}); patchInfo {{ type wall; }} }}\n'
    # A point inside the fluid: upstream of the body, on the centreline.
    px, py, pz = x0 + 0.5 * L, cy + half * 0.5, cz + half * 0.5

    wr(case, "system", "snappyHexMeshDict", "dictionary", f"""
castellatedMesh true;
snap            true;
addLayers       false;

geometry
{{
{geom}}}

castellatedMeshControls
{{
    maxLocalCells 2000000;
    maxGlobalCells 6000000;
    minRefinementCells 10;
    maxLoadUnbalance 0.10;
    nCellsBetweenLevels 3;
    features ();
    refinementSurfaces
    {{
{refs}    }}
    resolveFeatureAngle 30;
    refinementRegions {{}}
    locationInMesh ({px} {py} {pz});
    allowFreeStandingZoneFaces true;
}}

snapControls
{{
    nSmoothPatch 3;
    tolerance 2.0;
    nSolveIter 30;
    nRelaxIter 5;
    nFeatureSnapIter 10;
    implicitFeatureSnap false;
    explicitFeatureSnap true;
    multiRegionFeatureSnap false;
}}

addLayersControls
{{
    relativeSizes true;
    layers {{}}
    expansionRatio 1.2;
    finalLayerThickness 0.5;
    minThickness 0.1;
    nGrow 0;
    featureAngle 60;
    nRelaxIter 3;
    nSmoothSurfaceNormals 1;
    nSmoothNormals 3;
    nSmoothThickness 10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle 90;
    nBufferCellsNoExtrude 0;
    nLayerIter 50;
}}

meshQualityControls
{{
    maxNonOrtho 65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave 80;
    minVol 1e-13;
    minTetQuality 1e-15;
    minArea -1;
    minTwist 0.02;
    minDeterminant 0.001;
    minFaceWeight 0.05;
    minVolRatio 0.01;
    minTriangleTwist -1;
    nSmoothScale 4;
    errorReduction 0.75;
}}

mergeTolerance 1e-6;
""")

    walls = "body" + ("|plates" if plates is not None else "")
    k = 1.5 * (TURB_I * U) ** 2
    omega = k ** 0.5 / (0.09 ** 0.25 * 0.1 * L)

    def field(obj, cls, dims, internal, extra_wall):
        wr(case, "0", obj, cls, f"""
dimensions      {dims};
internalField   uniform {internal};
boundaryField
{{
    inlet    {{ type fixedValue; value uniform {internal}; }}
    outlet   {{ type zeroGradient; }}
    farfield {{ type slip; }}
    "{walls}" {{ {extra_wall} }}
}}
""")

    field("U", "volVectorField", "[0 1 -1 0 0 0 0]", f"({U} 0 0)",
          "type noSlip;")
    field("p", "volScalarField", "[0 2 -2 0 0 0 0]", "0",
          "type zeroGradient;")
    wr(case, "0", "p", "volScalarField", f"""
dimensions      [0 2 -2 0 0 0 0];
internalField   uniform 0;
boundaryField
{{
    inlet    {{ type zeroGradient; }}
    outlet   {{ type fixedValue; value uniform 0; }}
    farfield {{ type slip; }}
    "{walls}" {{ type zeroGradient; }}
}}
""")
    field("k", "volScalarField", "[0 2 -2 0 0 0 0]", f"{k:.6e}",
          f"type kqRWallFunction; value uniform {k:.6e};")
    field("omega", "volScalarField", "[0 0 -1 0 0 0 0]", f"{omega:.6e}",
          f"type omegaWallFunction; value uniform {omega:.6e};")
    field("nut", "volScalarField", "[0 2 -1 0 0 0 0]", "0",
          "type nutkWallFunction; value uniform 0;")

    wr(case, "constant", "transportProperties", "dictionary",
       f"transportModel  Newtonian;\nnu              {NU};\n")
    wr(case, "constant", "turbulenceProperties", "dictionary",
       "simulationType  RAS;\nRAS\n{\n    RASModel        kOmegaSST;\n"
       "    turbulence      on;\n    printCoeffs     on;\n}\n")

    area = frontal_area(tris)
    wr(case, "system", "controlDict", "dictionary", f"""
application     simpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         1500;
deltaT          1;
writeControl    timeStep;
writeInterval   500;
purgeWrite      2;
writeFormat     ascii;
writePrecision  7;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable false;
""")

    wr(case, "system", "fvSchemes", "dictionary", """
ddtSchemes      { default steadyState; }
gradSchemes     { default cellLimited Gauss linear 1; }
divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div(phi,k)      bounded Gauss upwind;
    div(phi,omega)  bounded Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear limited corrected 0.33; }
interpolationSchemes { default linear; }
snGradSchemes   { default limited corrected 0.33; }
wallDist        { method meshWave; }
""")

    wr(case, "system", "fvSolution", "dictionary", """
solvers
{
    p
    {
        solver          GAMG;
        tolerance       1e-7;
        relTol          0.01;
        smoother        GaussSeidel;
    }
    "(U|k|omega)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-8;
        relTol          0.1;
    }
}
SIMPLE
{
    nNonOrthogonalCorrectors 1;
    consistent      yes;
    residualControl { p 1e-4; U 1e-4; "(k|omega)" 1e-4; }
}
relaxationFactors
{
    equations { U 0.9; ".*" 0.9; }
}
""")

    wr(case, "system", "decomposeParDict", "dictionary",
       "numberOfSubdomains 4;\nmethod hierarchical;\n"
       "coeffs { n (4 1 1); }\n")

    return dict(case=os.path.relpath(case, ROOT), L_m=L, frontal_area_m2=area,
                U_inf=U, background_cells=nx * ny * nz, refine_level=lvl,
                domain=[[x0, y0, z0], [x1, y1, z1]], rho=RHO, nu=NU,
                reynolds=U * L / NU)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--fine", action="store_true")
    a = ap.parse_args()

    tris = np.concatenate([read_stl(os.path.join(STL, f))[1] for f in BODY])
    _, plates = read_stl(os.path.join(STL, PLATES))
    U = float(mm.shot(mm.thrust_constant()[0])["v_exit"])

    import json
    meta = {}
    for tag, pl in (("free", None), ("channel", plates)):
        name = f"{tag}_fine" if a.fine else tag
        meta[name] = build(os.path.join(HERE, name), tris, pl, U, a.fine)
        print(f"{name:12s} {meta[name]['background_cells']:>8d} background cells, "
              f"level {meta[name]['refine_level']}, "
              f"A_ref {meta[name]['frontal_area_m2']*1e4:.1f} cm^2, Re {meta[name]['reynolds']:.3g}")
    path = os.path.join(HERE, "case_meta.json")
    old = json.load(open(path)) if os.path.exists(path) else {}
    old.update(meta)
    json.dump(old, open(path, "w"), indent=2)
