// GENERATED by cad/tools/make_scad_params.py from cad/parameters.json.
// Do not edit by hand: edit parameters.json and re-run.
//
// Every numeric leaf of the parameter file appears here as <group>_<key>. The
// non-numeric ones are skipped and named below, so nothing is dropped silently.
//
// skipped (not numeric): envelope_status
// skipped (not numeric): envelope_reconciliation_note
// skipped (not numeric): envelope_espa_grande_conflict
// skipped (not numeric): track_status
// skipped (not numeric): stator_topology
// skipped (not numeric): stator_belt_sequence
// skipped (not numeric): stator_phase_colours_A
// skipped (not numeric): stator_phase_colours_B
// skipped (not numeric): stator_phase_colours_C
// skipped (not numeric): stator_end_turns_modelled
// skipped (not numeric): stator_end_turns_note
// skipped (not numeric): stator_layer_count_decision
// skipped (not numeric): stator_status
// skipped (not numeric): sled_status
// skipped (not numeric): sled_provisional_note
// skipped (not numeric): magazine_gate_pin_material
// skipped (not numeric): magazine_septum_material
// skipped (not numeric): magazine_shell_construction_decision
// skipped (not numeric): magazine_status
// skipped (not numeric): magazine_gate_pin_diameter_note
// skipped (not numeric): payload_cell_insert_divider_axis
// skipped (not numeric): payload_cell_section_limit_origin
// skipped (not numeric): payload_cell_classes_accommodated
// skipped (not numeric): payload_cell_classes_refused_ThinSat
// skipped (not numeric): payload_cell_classes_refused_12U CubeSat
// skipped (not numeric): payload_cell_classes_refused_ChipSat / femtosat
// skipped (not numeric): payload_cell_status
// skipped (not numeric): payload_cell_provisional_note
// skipped (not numeric): brake_ring_spring_stop
// skipped (not numeric): brake_taper_purpose
// skipped (not numeric): brake_status
// skipped (not numeric): brake_provisional_note
// skipped (not numeric): interface_espa_flange_protrudes_through_aft_skin
// skipped (not numeric): interface_espa_status
// skipped (not numeric): payload_3u_corner_rail_standard
// skipped (not numeric): payload_3u_modelled_as
// skipped (not numeric): payload_3u_status
// skipped (not numeric): enclosure_skin_material
// skipped (not numeric): enclosure_muzzle_aperture_verified
// skipped (not numeric): enclosure_aft_cutout_profile
// skipped (not numeric): enclosure_bays_verified_clear_of_track
// skipped (not numeric): enclosure_status
// skipped (not numeric): enclosure_mass_note
// skipped (not numeric): gen6_store_gas

brake_arrest_g_cap = 200;
brake_pole_count = 2;
brake_pole_plate_thickness = 15;
brake_pole_taper_entry_length = 30;
brake_pole_width_y = 90;
brake_x_end = 1740;
brake_x_start = 1530;
enclosure_aft_flange_cutout_diameter = 466;
enclosure_bays_avionics_sequencer_x = [610, 760];
enclosure_bays_avionics_sequencer_y = [-255, -135];
enclosure_bays_avionics_sequencer_z = [-130, -50];
enclosure_bays_imu_unit_x = [790, 850];
enclosure_bays_imu_unit_y = [-255, -195];
enclosure_bays_imu_unit_z = [-130, -80];
enclosure_bays_ppu_sic_inverter_x = [330, 580];
enclosure_bays_ppu_sic_inverter_y = [-255, -115];
enclosure_bays_ppu_sic_inverter_z = [-130, -30];
enclosure_bays_supercap_bank_96V_6F_x = [0, 300];
enclosure_bays_supercap_bank_96V_6F_y = [-255, -115];
enclosure_bays_supercap_bank_96V_6F_z = [-180, -30];
enclosure_belly_notch_x_max = 2;
enclosure_belly_notch_x_min = -27;
enclosure_belly_notch_y_half_width = 110;
enclosure_muzzle_aperture_centre_y = 0;
enclosure_muzzle_aperture_centre_z = 70;
enclosure_muzzle_aperture_height_z = 160;
enclosure_muzzle_aperture_width_y = 160;
enclosure_muzzle_panel_x = 1805;
enclosure_radiator_area_m2 = 0.32;
enclosure_radiator_length = 1600;
enclosure_radiator_thickness = 3;
enclosure_radiator_width = 200;
enclosure_radiator_x_start = 70;
enclosure_radiator_z = 707;
enclosure_skin_thickness = 2.0;
enclosure_x_max = 1807;
enclosure_x_min = -32;
enclosure_y_half_width = 265;
enclosure_z_bottom_skin_outer = -207;
enclosure_z_top_skin_outer = 707;
envelope_extremes_max_mm = [1807, 265, 710];
envelope_extremes_min_mm = [-32, -265, -230];
envelope_installed_closed_mm = [1839, 530, 940];
gen6_drive_acceleration_g = 25.0;
gen6_drive_bore_mm = 15.805;
gen6_drive_commanded_force_N = 981.0;
gen6_drive_cradle_contact_lever_mm = 170.25;
gen6_drive_cradle_preload_N_per_contact = 201.7;
gen6_drive_exit_velocity_m_s = 30.54;
gen6_drive_exit_velocity_m_s_at_friction_allowance = 29.01;
gen6_drive_exit_velocity_m_s_zero_friction = 30.54;
gen6_drive_piston_area_mm2 = 196.2;
gen6_drive_stroke_mm = 2180.0;
gen6_drive_tube_wall_mm = 1.0;
gen6_store_chamber_volume_l = 2.0;
gen6_store_charge_pressure_bar = 50.0;
gen6_store_fill_orifice_mm = 1.0;
gen6_store_first_fill_s = 4.14;
gen6_store_reservoir_volume_conduction_l = 8.95;
gen6_store_reservoir_volume_isothermal_l = 8.25;
gen6_store_reservoir_volume_l = 9.55;
gen6_store_storage_pressure_bar = 200.0;
interface_espa_bolt_circle_diameter = 400;
interface_espa_bolt_hole_count = 24;
interface_espa_bolt_hole_diameter = 9;
interface_espa_flange_outer_diameter = 460;
interface_espa_flange_thickness = 25;
interface_espa_gusset_count = 4;
interface_espa_gusset_inner_radius = 50;
interface_espa_gusset_outer_radius = 220;
interface_espa_gusset_thickness = 12;
interface_espa_hub_plate_diameter = 300;
interface_espa_hub_plate_thickness = 15;
interface_espa_x_max = 0;
interface_espa_x_min = -25;
magazine_cassette_height_z = 690;
magazine_cassette_length_x = 380.5;
magazine_cassette_width_y = 166;
magazine_drive_bay_width = 30;
magazine_escapement_finger_count = 2;
magazine_follower_plate_thickness = 6.0;
magazine_follower_rib_count = 3;
magazine_gate_ascent_preload_N = 5900;
magazine_gate_frame_z_max = 626;
magazine_gate_frame_z_min = 46;
magazine_gate_pin_count = 2;
magazine_gate_pin_diameter = 9;
magazine_gate_pin_x_positions = [110, 290];
magazine_leadscrew_x_position = 200;
magazine_satellite_pitch_z = 104;
magazine_satellites_per_cassette = 6;
magazine_septum_thickness = 1.0;
magazine_septum_x_max = 375;
magazine_septum_x_min = 25;
magazine_septum_z_max = 646;
magazine_septum_z_min = 26;
magazine_shell_panel_thickness = 4.0;
payload_3u_corner_rail_count = 4;
payload_3u_corner_rail_size = 8.5;
payload_3u_height_z = 100;
payload_3u_instances_in_assembly = 12;
payload_3u_length_x = 340.5;
payload_3u_width_y = 100;
payload_cell_cell_length_x = 340.5;
payload_cell_cell_pitch_z = 104.0;
payload_cell_cell_section_y = 100.0;
payload_cell_cell_section_z = 100.0;
payload_cell_cells_per_cassette = 6;
payload_cell_cells_total = 12;
payload_cell_insert_divider_thickness = 1.5;
sled_airgap_per_side = 1.0;
sled_backstop_thickness = 8.0;
sled_chassis_plate_thickness = 6.0;
sled_chassis_web_thickness = 6.0;
sled_chassis_web_y_inner = 48;
sled_chassis_web_y_outer = 54;
sled_gap_shim_tolerance = 0.05;
sled_halbach_array_length = 340;
sled_halbach_array_width_y = 90;
sled_halbach_array_x_end = 570;
sled_halbach_array_x_start = 230;
sled_halbach_array_z_inner = 6;
sled_halbach_array_z_outer = 14;
sled_halbach_magnet_thickness = 8;
sled_overall_height = 140;
sled_overall_length = 488;
sled_overall_width = 140;
sled_payload_com_offset_above_thrust_line = 70;
sled_roller_base_span = 300;
sled_roller_count = 4;
sled_roller_diameter = 30;
sled_roller_width = 16;
sled_roller_x_offset_from_centre = 125;
sled_roller_y_inner = 70;
sled_roller_y_outer = 86;
stator_active_span_end = 1296;
stator_active_span_start = 0;
stator_active_width_y = 90;
stator_belt_pitch = 8.0;
stator_belt_thickness_z = 10.0;
stator_belt_width = 7.0;
stator_belt_z_max = 5;
stator_belt_z_min = -5;
stator_conductor_count = 162;
stator_conductors_per_phase = 54;
stator_insulation_gap = 1.0;
stator_pole_pitch = 24;
stator_wavelength = 48;
stator_winding_fill_factor_for_mass = 0.6;
track_acceleration_zone_end = 1300;
track_guide_rail_y_inner = 68;
track_guide_rail_y_outer = 88;
track_guide_rail_z_contact = 15;
track_guide_rail_z_outer = 22;
track_guide_rails_per_side = 2;
track_launch_lock_count = 2;
track_launch_lock_x_end = 50;
track_launch_lock_x_start = 30;
track_launch_lock_y_inner = 68;
track_launch_lock_y_outer = 78;
track_launch_lock_z_half_height = 14;
track_longeron_count = 2;
track_longeron_length = 1800;
track_longeron_z_max = 20;
track_longeron_z_min = -45;
track_overall_width = 205;
track_release_point = 1500;
track_roller_channel_y_inner = 67;
track_roller_channel_y_outer = 90;
track_roller_channel_z_half_height = 22;
