"""Write cad/scad/parameters.scad from cad/parameters.json.

WHY THIS EXISTS
---------------
OpenSCAD has no JSON parser, so an OpenSCAD model of this machine could only get its
dimensions by having them typed into it. cad/parameters.json warns in its own header that
hand-carried dimensions "will silently drift", and ADR-015 says derive, never paste. A second
CAD implementation that pastes its numbers would be a second place for them to be wrong,
which is the opposite of what a cross-check is for.

So the parameter file is machine-written. Every numeric leaf of `groups` and `envelope` becomes a
top-level OpenSCAD variable named <group>_<key>. Non-numeric leaves are skipped and listed in
a comment, so what was dropped is visible rather than silent.

Usage:  python3 cad/tools/make_scad_params.py
"""
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "parameters.json")
OUT = os.path.join(HERE, "scad", "parameters.scad")


def numeric(v):
    return isinstance(v, (int, float)) and not isinstance(v, bool)


def emit(prefix, obj, lines, skipped):
    for k, v in obj.items():
        if k.startswith("_"):
            continue
        name = f"{prefix}_{k}" if prefix else k
        if numeric(v):
            lines.append(f"{name} = {v};")
        elif isinstance(v, list) and v and all(numeric(x) for x in v):
            lines.append(f"{name} = [{', '.join(str(x) for x in v)}];")
        elif isinstance(v, dict):
            emit(name, v, lines, skipped)
        else:
            skipped.append(name)


def main():
    p = json.load(open(SRC, encoding="utf-8"))
    lines, skipped = [], []
    emit("envelope", p["envelope"], lines, skipped)
    for group, body in p["groups"].items():
        emit(group, body, lines, skipped)

    head = [
        "// GENERATED by cad/tools/make_scad_params.py from cad/parameters.json.",
        "// Do not edit by hand: edit parameters.json and re-run.",
        "//",
        "// Every numeric leaf of the parameter file appears here as <group>_<key>. The",
        "// non-numeric ones are skipped and named below, so nothing is dropped silently.",
        "//",
    ]
    head += [f"// skipped (not numeric): {s}" for s in skipped]
    head.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(head + sorted(lines)) + "\n")
    print(f"wrote {os.path.relpath(OUT, os.path.dirname(HERE))}  "
          f"({len(lines)} values, {len(skipped)} non-numeric skipped)")


if __name__ == "__main__":
    main()
