"""Generate cad/DIMENSIONS.md and cad/BOM.md from the sources that already hold the data.

WHY THIS IS GENERATED
---------------------
A CAD agent reading this repository cross-references everything it finds and, in its own
words, "conflicts and gaps are where CAD goes wrong". A hand-written dimension table is a
second copy of `cad/parameters.json` that drifts from it -- which is precisely the failure
`parameters.json` exists to prevent between the nine Fusion documents. So the table is
derived, never typed: change `parameters.json`, re-run this, and the tables follow.

Masses and materials come from `analysis/mass_properties.py` by import, for the same reason
`cost.py` imports it rather than re-entering the numbers. That module is authoritative for
mass; duplicating it is how the operating point forked once already.

Run:  python3 cad/tools/make_cad_package.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CAD = os.path.dirname(HERE)
ROOT = os.path.dirname(CAD)
sys.path.insert(0, os.path.join(ROOT, "analysis"))

import mass_properties  # noqa: E402

STAMP = ("<!-- GENERATED by cad/tools/make_cad_package.py. Do not edit by hand:\n"
         "     edit cad/parameters.json or analysis/mass_properties.py and re-run. -->\n")

# Which group keys are dimensions rather than prose. Everything else in a group is a note,
# a status or a decision, and belongs in the notes column instead of the dimension table.
def is_dim(k, v):
    if k.startswith("_") or k in ("status", "topology"):
        return False
    if k.endswith(("_note", "_decision", "_purpose", "_verified", "_standard", "_sequence",
                   "_colours", "_material", "modelled_as")):
        return False
    return isinstance(v, (int, float, bool)) or (
        isinstance(v, list) and all(isinstance(x, (int, float)) for x in v))


def unit_for(k):
    if k.endswith(("_N", "_preload_N")):
        return "N"
    if k.endswith("_m2"):
        return "m^2"
    if k.endswith(("_count", "_per_side", "_per_phase", "_per_cassette", "_in_assembly",
                   "count", "_factor")):
        return "-"
    if k.endswith(("_g_cap",)):
        return "g"
    if isinstance(k, str) and ("fill" in k or "factor" in k):
        return "-"
    return "mm"


def dimensions_md(p):
    L = [STAMP, "# Dimensions\n",
         "Every dimension VOLLEY's geometry depends on, one table per sub-assembly, derived",
         "directly from [`parameters.json`](parameters.json) — the single source of truth.",
         "**Units are millimetres unless the table says otherwise.** Angles are degrees.\n",
         f"**Coordinate frame.** {p['_PROVENANCE']['coordinate_frame']}\n",
         "\n## Installed envelope\n",
         "| Quantity | Value | Units |", "|---|---:|---|"]
    e = p["envelope"]
    L.append(f"| Closed installed envelope (x, y, z) | {' x '.join(str(v) for v in e['installed_closed_mm'])} | mm |")
    L.append(f"| Extremes, minimum (x, y, z) | {', '.join(str(v) for v in e['extremes_min_mm'])} | mm |")
    L.append(f"| Extremes, maximum (x, y, z) | {', '.join(str(v) for v in e['extremes_max_mm'])} | mm |")
    L.append("")
    L.append(f"> **Open conflict, P9.** {e['espa_grande_conflict']}")
    L.append("> **Do not resolve this by shrinking the machine.** The geometry is supposed to state")
    L.append("> the problem rather than hide it; P9 is open and stays open until it is repackaged or")
    L.append("> the host class is re-scoped.\n")

    for gname, g in p["groups"].items():
        doc = g.get("_document", "").split("(")[0].strip()
        L.append(f"\n## {gname.replace('_', ' ')}\n")
        if doc:
            L.append(f"Fusion document: **`{doc}`**\n")
        if "topology" in g:
            L.append(f"Topology: {g['topology']}\n")
        L.append("| Parameter | Value | Units |")
        L.append("|---|---:|---|")
        for k, v in g.items():
            if not is_dim(k, v):
                continue
            val = ", ".join(str(x) for x in v) if isinstance(v, list) else str(v)
            L.append(f"| `{k}` | {val} | {unit_for(k)} |")
        mats = {k: v for k, v in g.items() if k.endswith("_material")}
        for k, v in mats.items():
            L.append(f"| `{k}` | {v} | — |")
        notes = [(k, v) for k, v in g.items()
                 if k.endswith(("_note", "_decision")) or k in ("modelled_as",)]
        if notes:
            L.append("")
            for k, v in notes:
                L.append(f"- **`{k}`** — {v}")
        st = g.get("status", "")
        if st:
            L.append(f"\n**Status:** `{st}`")
        L.append("")
    return "\n".join(L) + "\n"


# Material per line item. Read off mass_properties' own part names and box() densities;
# the lumped items carry no density, so they are named from the design rather than derived,
# and are marked as such.
DERIVED = {
    "Track longerons (2x Al box section)": ("Aluminium 7075-T6", "box section, 4 mm wall"),
    "Stator copper (1.3 m, 60% fill)": ("Copper, oxygen-free", "162 conductors, 3-phase"),
    "Stator formers / potting (PEEK eq.)": ("PEEK, unfilled", "formers and potting"),
    "Sled Halbach magnets (2 faces)": ("NdFeB N45SH, sintered", "two faces, 8 mm thick"),
    "Sled Ti chassis (shell equivalent)": ("Ti-6Al-4V grade 5", "plate, see note below"),
    "Sled rollers / latch / backstop": ("Steel 440C + Al", "4 rollers, D30 x 16"),
    "Eddy brake magnets + yoke": ("NdFeB + steel yoke", "2 tapered pole plates"),
    "Fixed brake hardware + ring spring (moving Cu fin is in sled)": ("Steel", "ring-spring stop"),
    "Cassette shells (2x Al sheet eq.)": ("Aluminium sheet", "see shell_construction_decision"),
    "Followers, gates, escapements (2x)": ("Al + A-286 pins", "2 gate pins D9 per cassette"),
    "Supercapacitor cells + busbars": ("—", "96 V, 6 F bank"),
    "PPU (SiC bridge, filters)": ("—", "SiC inverter"),
    "Battery + avionics + IMU": ("—", "sequencer, IMU"),
    "Harness": ("—", "—"),
    "Thermal (pipes, radiator, MLI)": ("Al radiator", "0.32 m^2 radiator"),
    "ESPA bracket + fasteners": ("Aluminium", "ring flange, 24 x M8 holes"),
    "Panels / closeouts": ("Aluminium, 2 mm skin", "enclosure"),
    "Sled CAD reconciliation (P15, CAD-derived 9.445 kg)": ("—", "see note"),
}


def bom_md(p):
    m_tot, cg, sled = mass_properties.build()
    L = [STAMP, "# Bill of materials\n",
         "**Masses are imported from [`analysis/mass_properties.py`](../analysis/mass_properties.py)**,",
         "which builds the rollup from primitive solids and material densities. Nothing here is",
         "re-entered by hand. Quantities and interface dimensions come from",
         "[`parameters.json`](parameters.json).\n",
         "> **No line item has a vendor quotation.** `analysis/cost.py` carries assumed prices and",
         "> says so in its own header; **no cost claim in this repository is supported**, and none",
         "> should be made from this table. It is a mass and materials list, not a purchase order.\n",
         "> **This rollup is incomplete.** The enclosure, radiator and packaged avionics have no",
         "> line items — open problem **P10**. Dry mass below is therefore a floor, not a total.\n",
         "| # | Item | Qty | Material | Mass, kg | CG x, m | Notes |",
         "|---:|---|---:|---|---:|---:|---|"]
    for i, (name, m, cgx) in enumerate(mass_properties.parts, 1):
        mat, note = DERIVED.get(name, ("—", "—"))
        qty = "2" if "2x" in name else "1"
        L.append(f"| {i} | {name} | {qty} | {mat} | {m:.2f} | {cgx:.2f} | {note} |")
    L.append(f"| | **DRY TOTAL** | | | **{m_tot:.1f}** | **{cg:.2f}** | P10: incomplete |")
    L.append(f"| | **LOADED** (12 x 3U at 4 kg) | | | **{m_tot + 48:.1f}** | | |")
    L.append("")
    L.append(f"**Sled assembly: {sled:.2f} kg**, the CAD-derived value from the Gen3 STEP solids (P15).")
    L.append("This is the single mass the exit velocity is most sensitive to, and it is the mass of")
    L.append("**unpocketed, as-drawn plates**. Lightening the sled in CAD changes the operating point:")
    L.append("re-run `mass_properties.py` and then `motor_model.py` before quoting any number after")
    L.append("such a change. See P5, P8, P15.\n")

    L.append("## Off-the-shelf and standards-bound items\n")
    L.append("| Item | Spec | Source |")
    L.append("|---|---|---|")
    mg = p["groups"]["magazine"]
    ie = p["groups"]["interface_espa"]
    pl = p["groups"]["payload_3u"]
    L.append(f"| Gate pins | {mg['gate_pin_count']} per cassette, D{mg['gate_pin_diameter']} mm, {mg['gate_pin_material']} | A22 resize, P37 |")
    L.append(f"| Cassette septa | {mg['septum_thickness']} mm {mg['septum_material']} | parameters.json |")
    L.append(f"| ESPA flange bolts | {ie['bolt_hole_count']} x D{ie['bolt_hole_diameter']} mm on a D{ie['bolt_circle_diameter']} mm circle | ESPA ring interface |")
    L.append(f"| Payload envelope | {pl['length_x']} x {pl['width_y']} x {pl['height_z']} mm, {pl['corner_rail_size']} mm rails | {pl['corner_rail_standard']} |")
    L.append("")
    return "\n".join(L) + "\n"


def main():
    p = json.load(open(os.path.join(CAD, "parameters.json")))
    for fn, body in (("DIMENSIONS.md", dimensions_md(p)), ("BOM.md", bom_md(p))):
        with open(os.path.join(CAD, fn), "w") as fh:
            fh.write(body)
        print(f"  wrote cad/{fn}  ({len(body.splitlines())} lines)")


if __name__ == "__main__":
    main()
